### ISSUE TITLE
Missing string status_help

### ISSUE THREAD

**Issue by vmdef** [cbluesprl/moodle-enrol_shared#1]
Hi!

If I edit the configuration of a plugin instance in a course, I get the message (developer level debugging enabled): 

> Help contents string does not exist: [status_help, enrol_shared]
> 
> - line 502 of /lib/outputcomponents.php: call to debugging()
> - line 2405 of /lib/outputrenderers.php: call to help_icon->diag_strings()
> - line 2131 of /lib/formslib.php: call to core_renderer->help_icon()
> - line 255 of /enrol/shared/lib.php: call to MoodleQuickForm->addHelpButton()
> - line 52 of /enrol/editinstance_form.php: call to enrol_shared_plugin->edit_instance_form()
> - line 214 of /lib/formslib.php: call to enrol_instance_edit_form->definition()
> - line 69 of /enrol/editinstance.php: call to moodleform->__construct()

Cheers,
Víctor

**Comment by Trolli07** [comment]
Hello,

Thank you for your feedback.

I made a general commit for the 3 issues and I took the opportunity to beautify the code.

Best regards,

Olivier
