### ISSUE TITLE
expirynotify and expirythreshold undefined

### ISSUE THREAD

**Issue by vmdef** [cbluesprl/moodle-enrol_shared#2]
Hi!

If I save the configuration of a plugin instance in a course, I get the messages (developer level debugging enabled):

> Notice: Undefined index: expirynotify
> ...
> Notice: Undefined index: expirythreshold

Cheers,
Víctor

**Comment by Trolli07** [comment]
Hello,

Thank you for your feedback.

I made a general commit for the 3 issues and I took the opportunity to beautify the code.

Best regards,

Olivier
