### ISSUE TITLE
Enrolment status "Not current"

### ISSUE THREAD

**Issue by vmdef** [cbluesprl/moodle-enrol_shared#3]
Hi!

It may not be a bug but a misconfiguration in my environment or a misunderstanding on my side.

According to the _Default enrolment duration_ description (default settings) and the _Default enrolment duration_ (instance settings), if they are set to 0 or disabled, the enrolment duration will be unlimited.

However, if I set to zero the default setting and/or disabled the instance one, the user can't access the course because _Enrolment ends_ value is enabled and set to the same value as the _Enrolment created_ value. If a set any value to _Default enrolment duration_, the user can access the course.

Cheers,
Víctor

**Comment by Trolli07** [comment]
Hello,

Thank you for your feedback.

I made a general commit for the 3 issues and I took the opportunity to beautify the code.

Best regards,

Olivier

**Comment by vmdef** [comment]
Hi @Trolli07,

Thanks for working on these issues. It would be great if you could add the new version in the Moodle plugins directory when it is ready.

Regards,
Víctor
